baseurl = "http://www.arnaudbos.com/"
languageCode = "en-US"
title = "Arnaud Bos"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Arnaud Bos"
  description = "My corner of the interweb."
  projects = "http://side-effects.arnaudbos.com/"
  resume = "http://vitae.arnaudbos.com/"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[social]
  Github        = "arnaudbos"
  Email         = "mail@arnaudbos.com"
  Twitter       = "arnaud_bos"
  LinkedIn      = "arnaudbos"
  Stackoverflow = "story/arnaudbos"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "http://i-rant.arnaudbos.com/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "http://side-effects.arnaudbos.com/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "http://vitae.arnaudbos.com/"
